# starship config

add_newline = true

[character]
success_symbol = "[➜](bold yellow)"
error_symbol = "[✖](bold red) "

[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = "-"
style = "bold dimmed green"
disabled = false

[time]
time_format = "%T"
format = "🚀 $time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false

[rust]
format = "via [$symbol($version )]($style)"
symbol = "🐢 "
style = "bold yellow"